#!/usr/bin/env NODE_PATH=.:$NODE_PATH node

var find    = require('.')
var debug   = require('gulp-debug')
var drain   = require('./drain')
var through = require('through2')

var argv = require('yargs')
.demand(1)
.usage('$0 [options] path [path...]')
.describe('max-depth', 'Limit depth of recursion.')
.alias('insensitive', 'i')
.describe('insensitive', 'Turn off case sensitivity.')
.help('help', 'Show this help and exit.')
.argv

var opts = argv
opts.start = argv._

find(opts)
.pipe(through.obj(function(entry, enc, next) {
  console.log(entry.path)
  next()
}))
.pipe(drain.objs)

